<?php

/** @see \GotChange_Filter_UKCurrencyToPence */
require_once APPLICATION_PATH . '/filters/UKCurrencyToPence.php';

/**
 * Test class for GotChange_Filter_UKCurrencyToPence.
 * Generated by PHPUnit on 2011-09-25 at 15:33:28.
 */
class GotChange_Filter_UKCurrencyToPenceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var GotChange_Filter_UKCurrencyToPence
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GotChange_Filter_UKCurrencyToPence();
    }

    /**
     * test filter with a pence value
     */
    public function testFilterWithPence()
    {
        // assign
        $expected = (float) 123;
        $input = '123p';
        
        // act
        $actual = $this->object->filter($input);
        
        // assert
        $this->assertEquals($expected, $actual);
    }
    
    /**
     * test filter with a pound value
     */
    public function testFilterWithPound()
    {
        // assign
        $expected = (float) 123;
        $input = 'Â£1.23p';
        
        // act
        $actual = $this->object->filter($input);
        
        // assert
        $this->assertEquals($expected, $actual);
    }
    

}