<?php

/** @see ControllerTestCase */
require_once 'ControllerTestCase.php';

/** @see ErrorController */
require_once APPLICATION_PATH . '/controllers/ErrorController.php';

/**
 * Test class for ErrorController.
 * Generated by PHPUnit on 2011-09-25 at 16:39:47.
 */
class ErrorControllerTest extends ControllerTestCase
{
    /**
     * test a 404 error
     */
    public function testError404()
    {
        $this->dispatch('/foo/bar');
        $this->assertController('error');
        $this->assertAction('error');
        $this->assertResponseCode(404);
    }
}